### ISSUE TITLE
Question about subdirectories

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-midterm#10]
Within the separation of `code`, `docs`, and `data` directories, is it okay to use subdirectories to keep things neat (with docs to note the file structure) or would you prefer if we left them flat?

**Comment by HeshamElsaman** [comment]
If we keep them separated, is there an easy way to do imports without needing other libraries and/or functions?

**Comment by laserlab** [comment]
@avgagliardo You can definitely use subdirectories. 
@HeshamElsaman Not sure what you mean? Do you mean import of libraries or reading the data files? For data files you can just use relative paths.

**Comment by HeshamElsaman** [comment]
@laserlab 
Yes, apologies, I figured that out.
