### ISSUE TITLE
Question about distance calculation task

### ISSUE THREAD

**Issue by p-pxmpo** [ubsuny/CP1-24-midterm#11]
This task is not clear, are we supposed to calculate the distance between every point recorded in our data? Do we pick two points from the data? which two points are we supposed to calculate the distance of?

**Comment by HeshamElsaman** [comment]
It's stated that the two points are adjacent. I assumed that the task is to calculate the distance between every two adjacent points and store it into an array.

**Comment by laserlab** [comment]
you just need a function that can calculate the distance between any two adjacent points as @HeshamElsaman and the midterm description states. You are not supposed to calculate the distance between all points for this task.

**Comment by laserlab** [comment]
> It's stated that the two points are adjacent. I assumed that the task is to calculate the distance between every two adjacent points and store it into an array.
Only the first part of your answer is correct. You do not have to store the results in an array.
