### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by haiderabbas007** [ubsuny/CP1-24-midterm#13]
In the naming of the markdown file 
![image](https://github.com/user-attachments/assets/8b82e215-e550-4e25-9463-43027a7997f2)

what is the unique id?

**Comment by haiderabbas007** [comment]
I tried to retrieve an ID from https://api.github.com/users/haiderabbas007
![image](https://github.com/user-attachments/assets/40b0abaf-fd81-4c1d-88c8-161453f3a772)

Is it this one that I should use?

**Comment by laserlab** [comment]
No, you can make it up yourself as described in the midterm description
