### ISSUE TITLE
How-to-report questions

### ISSUE THREAD

**Issue by HeshamElsaman** [ubsuny/CP1-24-midterm#7]
1. What's the format of reporting the direction of motion?
2. Are we supposed to record the weather conditions manually, or is there an easy way to do it?

**Comment by laserlab** [comment]
1. A vector
2. you can choose

**Comment by HeshamElsaman** [comment]
For 1, so like we need to report the direction of motion at each point in time or for the whole journey?

**Comment by laserlab** [comment]
> For 1, so like we need to report the direction of motion at each point in time or for the whole journey?

For each point since you need it for plotting it over time

**Comment by haiderabbas007** [comment]
would it be like generating a bunch of 3-tuples, each representing a vector at a single point in space and time, like (acceleration x, acceleration y, acceleration z) for all points?
